services:
  frontend:
    build:
      context: ../accessibility-focused-website
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ../news-api
    ports:
      - "5000:5000"
